[[plugins]] #dein 
repo = 'Shougo/dein.vim'

[[plugins]] # colorscheme molokai
repo = 'tomasr/molokai'
hook_add = '''
	au MyAutoCmd VimEnter * nested colorscheme molokai
''' 

[[plugins]] # denite
repo = 'Shougo/denite.nvim' 

[[plugins]] # comment
repo = 'tyru/caw.vim'
hook_add = '''
	nmap <C-K> <Plug>(caw:zeropos:toggle)
	vmap <C-K> <Plug>(caw:zeropos:toggle)
'''

[[plugins]] # deoplete
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''
