[[plugins]] #dein 
repo = 'Shougo/dein.vim'

[[plugins]] # colorscheme molokai
repo = 'tomasr/molokai'
hook_add = '''
	au MyAutoCmd VimEnter * nested colorscheme molokai
''' 

[[plugins]] # comment
repo = 'tyru/caw.vim'
hook_add = '''
	nmap <C-K> <Plug>(caw:zeropos:toggle)
	vmap <C-K> <Plug>(caw:zeropos:toggle)
'''
