[[plugins]] #dein 
repo = 'Shougo/dein.vim'

[[plugins]] # colorscheme molokai
repo = 'tomasr/molokai'
hook_add = '''
	au MyAutoCmd VimEnter * nested colorscheme molokai
''' 

[[plugins]] # denite
repo = 'Shougo/denite.nvim' 

[[plugins]] # comment
repo = 'tyru/caw.vim'
hook_add = '''
	nmap <C-K> <Plug>(caw:hatpos:toggle)
	vmap <C-K> <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
