[[plugins]] # toml
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]] # go
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
	let g:go_metalinter_autosave = 1
'''

[[plugins]] # ruby
repo = 'Shougo/deoplete-rct'
on_ft = ['ruby']

[[plugins]] # from deoplete's README
repo = 'roxma/nvim-yarp'
if = '!has("nvim")'

[[plugins]] # from deoplete's README
repo = 'roxma/vim-hug-neovim-rpc'
if = '!has("nvim")'

